### ISSUE TITLE
README

### ISSUE THREAD

**Issue by aaronliu0130** [aaronliu0130/schedule#5]
There is no README.md file in the repository right now. It would be good for visitors to see what this is.

**Comment by jerronl** [comment]
just create a file with "README.md" as its name. You can make a plain text file, or if you like, you can add fancy formatting after https://guides.github.com/features/mastering-markdown/

**Comment by aaronliu0130** [comment]
I know. I saw that it's a good practice to open an issue to another branch.

**Comment by aaronliu0130** [comment]
@jerronl You can also review the file.
